name: File Sync

on:
  push:
    branches:
      - main
  schedule:
    - cron: 0 0 * * *

jobs:
  file_sync:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: File Sync
        uses: kbrashears5/github-action-file-sync@master
        with:
          PULL_REQUEST_BRANCH_NAME: main
          REPOSITORIES: |
            inoa-io/camel-integrations
          FILES: |
            file-sync/workflows/dependabot.yaml=.github/workflows/dependabot.yaml
          TOKEN: ${{ secrets.GIT_ACTION_TOKEN }}
